# This file was generated by GoReleaser. DO NOT EDIT.
cask "sieve" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "e0525a8e7a982599e0e55cbdff056e86038ff30c79c4a27cfba007ce35ef8363"
      url "https://github.com/gnanam1990/sieve/releases/download/v#{version}/sieve_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8038e32ddfd1952f3b41f0cbd46b60d58b7348cf9c1962d3bc6b34cd94549a55"
      url "https://github.com/gnanam1990/sieve/releases/download/v#{version}/sieve_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b5f397e9d08943785b8c6fe8c925410eb1ac6ccf58a0296ae59eae774feec221"
      url "https://github.com/gnanam1990/sieve/releases/download/v#{version}/sieve_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e0832a52b284d3e80fd4e5cc23f994116bbc71e95ed44ed0e33c181007882fe"
      url "https://github.com/gnanam1990/sieve/releases/download/v#{version}/sieve_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sieve"
  desc "Zero-infra, provider-agnostic PR reviewer"
  homepage "https://github.com/gnanam1990/sieve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sieve"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sieve"]
    end
  end

  # No zap stanza required

end
