# This file was generated by GoReleaser. DO NOT EDIT.
cask "sieve" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "dd49ac90bc9864a16469a2125ec0521ec83fcc85259c80ba6ac4aadbe3b09a60"
      url "https://github.com/gnanam1990/sieve/releases/download/v#{version}/sieve_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf97088b08539030f73c45c7a61379f6d9b59b16a0113190da90d1bfc628d6d8"
      url "https://github.com/gnanam1990/sieve/releases/download/v#{version}/sieve_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3475320c8456b98de7b51dd5dd59d2b70c5c5a83536bae604e23ce430508663"
      url "https://github.com/gnanam1990/sieve/releases/download/v#{version}/sieve_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bfd2230ad5af73340a5450f5535f14c25a29d06fa5f13fbb43d7c8361286ebec"
      url "https://github.com/gnanam1990/sieve/releases/download/v#{version}/sieve_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sieve"
  desc "Zero-infra, provider-agnostic PR reviewer"
  homepage "https://github.com/gnanam1990/sieve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sieve"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sieve"]
    end
  end

  # No zap stanza required

end
