# This file was generated by GoReleaser. DO NOT EDIT.
cask "sieve" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "345d8e3c5ca51dde252d13e88d9a287fbba4df6122aab877837276b914acfa94"
      url "https://github.com/gnanam1990/sieve/releases/download/v#{version}/sieve_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "196247b72ceccccee4d1d221534507b70130798b101dacd1361ca9508366b8ad"
      url "https://github.com/gnanam1990/sieve/releases/download/v#{version}/sieve_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fafdd3c6ae6998745520a968c51c420446c463da6363eb9ea30ed8483060c7d3"
      url "https://github.com/gnanam1990/sieve/releases/download/v#{version}/sieve_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "92e9f709d78b36418bdcd092179624272d7298933f24e9bcd7de6502b888f82a"
      url "https://github.com/gnanam1990/sieve/releases/download/v#{version}/sieve_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sieve"
  desc "Zero-infra, provider-agnostic PR reviewer"
  homepage "https://github.com/gnanam1990/sieve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sieve"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sieve"]
    end
  end

  # No zap stanza required

end
